[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    ESP32Async/ESPAsyncWebServer @ ^3.0.6
    ESP32Async/AsyncTCP @ ^3.2.0
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.7
    bblanchon/ArduinoJson @ ^7.0.4
